#pragma once

/**
 * @defgroup sec_config Security Component Configuration
 * @brief Configuration macros for the security component.
 *
 * These macros define compile-time parameters used by the security subsystem.
 * The values must be consistent with the underlying cryptographic implementations
 * provided by the consumer.
 *
 * @{
 */

/**
 * @brief Size of the cryptographic hash output in bytes.
 *
 * Defines the expected size of the hash produced by the `_sec_hash` callback.
 *
 * @note This must match the output size of the selected hash algorithm
 *       (e.g., 32 bytes for SHA-256).
 *
 * @warning Mismatch between this value and the actual hash implementation
 *          may lead to verification failures or security vulnerabilities.
 */
#define SEC_HASH_SIZE               32

/**
 * @brief Size of the nonce in bytes.
 *
 * Defines the required size of nonces generated by the `_sec_nonce` callback.
 *
 * @note The nonce size must meet the requirements of the cryptographic
 *       algorithms in use (e.g., 12 or 16 bytes depending on the scheme).
 *
 * @warning Using an incorrect nonce size may break encryption security
 *          guarantees or cause runtime failures.
 */
#define SEC_NONCE_SIZE              16

/** @} */ /* end of sec_config */